import { useCallback, useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { getReport } from "../api/reports";
import { ApiError } from "../api/client";
import ErrorBox from "../components/ErrorBox";
import { formatDateTime, shortHash } from "../state/format";
import { REPORT_SECTION_ORDER } from "../types/models";
import type { ReportDetail, ReportSectionName } from "../types/models";

const HEADINGS: Record<ReportSectionName, string> = {
  header: "Report header",
  executive_summary: "Executive summary",
  evidence_inventory: "Evidence inventory",
  integrity_verification: "Integrity verification",
  processing_summary: "Processing summary",
  key_findings: "Key findings",
  finding_traceability: "Finding traceability",
  cross_source_correlation: "Cross-source correlation",
  activity_groups: "Activity groups",
  incident_timeline: "Incident timeline",
  evidence_graph_summary: "Evidence graph summary",
  investigator_review: "Investigator review",
  ai_ml_explanation: "AI / ML explanation",
  investigation_conclusion: "Investigation conclusion",
  limitations: "Limitations",
};

const FIELD_LABELS: Record<string, string> = {
  report_id: "Report ID",
  case_id: "Case ID",
  report_title: "Report title",
  case_name: "Case name",
  case_status: "Case status",
  case_severity: "Case severity",
  investigator: "Investigator",
  report_version: "Report version",
  schema: "Schema",
  status: "Status",
  generated_by: "Generated by",
  generated_at: "Generated at",
  title: "Title",
  finding_id: "Finding ID",
  evidence_id: "Evidence ID",
  original_filename: "Filename",
  evidence_type: "Evidence type",
  mime_type: "MIME type",
  file_size: "Size (bytes)",
  sha256: "Recorded SHA-256",
  recorded_sha256: "Recorded SHA-256",
  computed_hash: "Computed SHA-256",
  expected_hash: "Recorded SHA-256",
  checked_at: "Checked at",
  actor: "Actor",
  uploaded_at: "Uploaded at",
  created_at: "Created at",
  updated_at: "Updated at",
  started_at: "Started at",
  completed_at: "Completed at",
  run_count: "Processing runs",
  records_received: "Records received",
  records_normalized: "Records normalized",
  records_rejected: "Records rejected",
  total: "Total",
  rule_findings: "Rule findings",
  ml_findings: "ML findings",
  event_count: "Events",
  evidence_count: "Evidence sources",
  confidence: "Confidence",
  severity: "Severity",
  status_label: "Status",
  rule_id: "Rule",
  run_id: "Run",
  total_score: "Score",
  author: "Author",
  body: "Body",
  statement: "Statement",
  explanation: "Explanation",
  note: "Note",
  overview: "Overview",
  entry_type: "Entry type",
  timestamp: "Timestamp",
  event_id: "Event ID",
  raw_record_id: "Raw record ID",
  relation: "Relation",
  source: "Source",
  target: "Target",
  significance: "Significance",
  count: "Count",
  kind: "Kind",
  label: "Label",
};

const isHashKey = (key: string): boolean => /hash|sha256/i.test(key);
const isIsoKey = (key: string): boolean =>
  /_at$|_time$|timestamp|checked_at|generated_at/i.test(key);

function humanLabel(key: string): string {
  return FIELD_LABELS[key] ?? key.replace(/_/g, " ");
}

function isPlainValue(value: unknown): boolean {
  return (
    value === null ||
    value === undefined ||
    typeof value === "string" ||
    typeof value === "number" ||
    typeof value === "boolean"
  );
}

function cellText(value: unknown, key: string): string {
  if (value === null || value === undefined) return "—";
  if (typeof value === "boolean") return value ? "yes" : "no";
  if (typeof value === "number") return String(value);
  if (typeof value === "string") {
    if (isHashKey(key) && value.length > 24) return shortHash(value);
    if (isIsoKey(key) && value.includes("T")) return value;
    return value;
  }
  return JSON.stringify(value);
}

type JsonRow = Record<string, unknown>;

function SectionTable({ rows }: { rows: JsonRow[] }): JSX.Element {
  const columns = Array.from(new Set(rows.flatMap((row) => Object.keys(row))));
  if (columns.length === 0) {
    return <p className="font-mono text-[11px] text-slate-600">— empty —</p>;
  }
  return (
    <div className="overflow-x-auto">
      <table className="w-full border-collapse text-xs">
        <thead>
          <tr className="border-b border-slate-800 text-left font-mono text-[10px] uppercase tracking-widest text-slate-500">
            {columns.map((column) => (
              <th key={column} className="py-2 pr-4">
                {humanLabel(column)}
              </th>
            ))}
          </tr>
        </thead>
        <tbody>
          {rows.map((row, index) => (
            <tr key={index} className="border-b border-slate-900 align-top">
              {columns.map((column) => {
                const value = row[column];
                if (isHashKey(column) && typeof value === "string" && value.length > 24) {
                  return (
                    <td key={column} className="py-2 pr-4">
                      <code className="font-mono text-[10px] text-slate-400" title={value}>
                        {shortHash(value)}
                      </code>
                    </td>
                  );
                }
                if (isPlainValue(value)) {
                  return (
                    <td key={column} className="py-2 pr-4 text-slate-300">
                      {cellText(value, column)}
                    </td>
                  );
                }
                return (
                  <td key={column} className="py-2 pr-4 font-mono text-[10px] text-slate-500">
                    {JSON.stringify(value)}
                  </td>
                );
              })}
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

function FieldBlock({ label, text }: { label: string; text: string }): JSX.Element {
  return (
    <div>
      <p className="font-mono text-[10px] uppercase tracking-widest text-slate-500">{label}</p>
      <p className="mt-1 whitespace-pre-wrap text-sm leading-relaxed text-slate-300">{text}</p>
    </div>
  );
}

function SectionBody({ data }: { data: JsonRow }): JSX.Element {
  return (
    <div className="mt-4 space-y-5">
      {Object.entries(data).map(([key, value]) => {
        if (Array.isArray(value)) {
          const objects = value.filter(
            (item): item is JsonRow => item !== null && typeof item === "object" && !Array.isArray(item),
          );
          const scalars = value.filter((item) => isPlainValue(item));
          return (
            <div key={key}>
              <p className="font-mono text-[10px] uppercase tracking-widest text-slate-500">
                {humanLabel(key)} {`(${value.length})`}
              </p>
              <div className="mt-2">
                {objects.length > 0 ? (
                  <SectionTable rows={objects} />
                ) : (
                  <ul className="list-inside list-disc space-y-1 text-sm text-slate-300">
                    {scalars.map((item, index) => (
                      <li key={index}>{cellText(item, key)}</li>
                    ))}
                    {scalars.length === 0 && (
                      <li className="font-mono text-[11px] text-slate-600">— empty —</li>
                    )}
                  </ul>
                )}
              </div>
            </div>
          );
        }
        if (value !== null && typeof value === "object") {
          return (
            <div key={key}>
              <p className="font-mono text-[10px] uppercase tracking-widest text-slate-500">
                {humanLabel(key)}
              </p>
              <div className="mt-2 grid gap-x-6 gap-y-2 sm:grid-cols-2">
                {Object.entries(value as JsonRow).map(([nestedKey, nestedValue]) => (
                  <div key={nestedKey} className="flex items-start justify-between gap-3 border-b border-slate-900 pb-1">
                    <span className="font-mono text-[10px] uppercase tracking-widest text-slate-500">
                      {humanLabel(nestedKey)}
                    </span>
                    <span className="text-right text-xs text-slate-300">
                      {cellText(nestedValue, nestedKey)}
                    </span>
                  </div>
                ))}
              </div>
            </div>
          );
        }
        return <FieldBlock key={key} label={humanLabel(key)} text={cellText(value, key)} />;
      })}
    </div>
  );
}

export default function ReportDetailPage(): JSX.Element {
  const { caseId = "", reportId = "" } = useParams();

  const [report, setReport] = useState<ReportDetail | null>(null);
  const [error, setError] = useState<string | null>(null);

  const load = useCallback(() => {
    getReport(caseId, reportId)
      .then(setReport)
      .catch((err: unknown) => {
        setError(err instanceof ApiError ? err.message : "Failed to load the report.");
      });
  }, [caseId, reportId]);

  useEffect(() => {
    load();
  }, [load]);

  if (error) {
    return <ErrorBox message={error} />;
  }
  if (!report) {
    return <p className="font-mono text-xs uppercase tracking-widest text-slate-500">Loading report…</p>;
  }

  return (
    <div className="report-print space-y-6">
      <div className="print-hide flex flex-wrap items-start justify-between gap-4">
        <div>
          <p className="font-mono text-xs uppercase tracking-widest text-cyan-500">
            {report.case_id} · {report.report_id}
          </p>
          <h1 className="mt-1 text-2xl font-bold text-white">{report.title}</h1>
          <p className="mt-1 font-mono text-[11px] text-slate-400">
            {report.schema} · v{report.report_version} · {report.status} · generated by{" "}
            {report.generated_by} · {report.generated_at ? formatDateTime(report.generated_at) : "—"}
          </p>
        </div>
        <div className="flex flex-wrap items-center gap-3">
          <button
            type="button"
            onClick={() => window.print()}
            className="border border-cyan-700 bg-cyan-950/60 px-4 py-2 font-mono text-xs uppercase tracking-widest text-cyan-300 hover:bg-cyan-900/60"
          >
            Print report
          </button>
          <Link
            to={`/cases/${caseId}/reports`}
            className="border border-slate-700 px-4 py-2 font-mono text-xs uppercase tracking-widest text-slate-400 hover:text-slate-200"
          >
            ← All reports
          </Link>
        </div>
      </div>

      <Link
        to={`/cases/${caseId}`}
        className="print-hide inline-block font-mono text-xs uppercase tracking-widest text-slate-500 hover:text-cyan-300"
      >
        ← Back to case
      </Link>

      {REPORT_SECTION_ORDER.map((name) => (
        <section
          key={name}
          className="report-section border border-slate-800 bg-slate-900/50 p-5"
        >
          <h2 className="font-mono text-xs uppercase tracking-[0.25em] text-slate-500">
            {HEADINGS[name]}
          </h2>
          <SectionBody data={report.sections[name]} />
        </section>
      ))}
    </div>
  );
}